# Generated by Django 4.0.4 on 2022-05-18 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BiLingoApp', '0004_category_question_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
